name: Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set File Permissions
        run: chmod +x postinstall_script.sh

      - name: Build osqueryd Package
        run: pkgbuild --root ./stagedfiles --scripts ./scripts --identifier com.vistar.myapp --version 1 --install-location /Applications mypackage.pkg

      - name: Upload the Installer Package as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: osquery.pkg
          path: mypackage.pkg
