name: Build macOS Installer Package

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2

    - name: Install necessary dependencies (if any)
      run: |
        # Add any commands to install dependencies, if needed
        # For example, if you're using Homebrew: brew install ...

    - name: Build the macOS installer package
      run: |
        # Run the commands to build the package using productbuild
        productbuild --distribution distribution.xml --package-path . output.pkg

    - name: Upload the package artifact
      uses: actions/upload-artifact@v2
      with:
        name: osquery-installer
        path: output.pkg
