name: Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build .pkg file
        run: npm run build
      - name: Upload .pkg file
        uses: actions/upload-artifact@v2
        with:
          name: my-app.pkg
          path: dist/*.pkg
